In [23]:
import sqlite3

connection = sqlite3.connect("books.db")

In [24]:
import pandas as pd
pd.options.display.max_columns = 10
pd.read_sql('SELECT * FROM authors', connection, index_col=['id'])

        first    last
id
1        Paul  Deitel
2      Harvey  Deitel
3       Abbey  Deitel
4         Dan   Quirk
5   Alexander    Wald

In [25]:
pd.read_sql("SELECT * FROM titles", connection)

         isbn                             title  edition copyright
0  0135404673     Intro to Python for CS and DS        1      2020
1  0132151006     Internet & WWW How to Program        5      2012
2  0134743350               Java How to Program       11      2018
3  0133976890                  C How to Program        8      2016
4  0133406954  Visual Basic 2012 How to Program        6      2014
5  0134601548          Visual C# How to Program        6      2017
6  0136151574         Visual C++ How to Program        2      2008
7  0134448235                C++ How to Program       10      2017
8  0134444302            Android How to Program        3      2017
9  0134289366         Android 6 for Programmers        3      2016

In [26]:
df = pd.read_sql('SELECT * FROM author_ISBN', connection)
df.head()

   id        isbn
0   1  0134289366
1   2  0134289366
2   5  0134289366
3   1  0135404673
4   2  0135404673

In [27]:
#retrieving only specific columns requires different than SELECT *
pd.read_sql('SELECT first, last FROM authors', connection)

       first    last
0       Paul  Deitel
1     Harvey  Deitel
2      Abbey  Deitel
3        Dan   Quirk
4  Alexander    Wald

In [28]:
# where clause finds predicates to satisfy certain selection criteria
pd.read_sql("""SELECT title, edition, copyright
FROM titles
WHERE copyright > '2016'""", connection)

                           title  edition copyright
0  Intro to Python for CS and DS        1      2020
1            Java How to Program       11      2018
2       Visual C# How to Program        6      2017
3             C++ How to Program       10      2017
4         Android How to Program        3      2017

In [29]:
#LIKE clause is for pattern matching
pd.read_sql("""SELECT id, first, last
FROM authors
WHERE last LIKE 'D%'""", connection, index_col=['id'])

     first    last
id
1     Paul  Deitel
2   Harvey  Deitel
3    Abbey  Deitel

In [30]:
#and underscore indicates a wildcard. % is account fill for rest
pd.read_sql("""SELECT id, first, last
FROM authors
WHERE first LIKE '_b%'""", connection, index_col=['id'])

    first    last
id
3   Abbey  Deitel

In [31]:
# order by is for ascending/descinding orders
pd.read_sql('SELECT title FROM titles ORDER BY title ASC', connection)

                              title
0         Android 6 for Programmers
1            Android How to Program
2                  C How to Program
3                C++ How to Program
4     Internet & WWW How to Program
5     Intro to Python for CS and DS
6               Java How to Program
7  Visual Basic 2012 How to Program
8          Visual C# How to Program
9         Visual C++ How to Program

In [32]:
#and do multiple columns by adding comma-separated value check
pd.read_sql("""SELECT id, first, last
FROM authors
ORDER BY last, first""",
            connection, index_col='id')

        first    last
id
3       Abbey  Deitel
2      Harvey  Deitel
1        Paul  Deitel
4         Dan   Quirk
5   Alexander    Wald

In [33]:
#can mix and match these orders by column
pd.read_sql("""SELECT id, first, last
FROM authors
ORDER BY last DESC, first ASC""",
            connection, index_col=['id'])

        first    last
id
5   Alexander    Wald
4         Dan   Quirk
3       Abbey  Deitel
2      Harvey  Deitel
1        Paul  Deitel

In [34]:
#where and order by can be combined
pd.read_sql("""SELECT isbn, title, edition, copyright
FROM titles
WHERE title LIKE '%How to Program'
ORDER BY title""", connection)

         isbn                             title  edition copyright
0  0134444302            Android How to Program        3      2017
1  0133976890                  C How to Program        8      2016
2  0134448235                C++ How to Program       10      2017
3  0132151006     Internet & WWW How to Program        5      2012
4  0134743350               Java How to Program       11      2018
5  0133406954  Visual Basic 2012 How to Program        6      2014
6  0134601548          Visual C# How to Program        6      2017
7  0136151574         Visual C++ How to Program        2      2008

In [35]:
#merge data output with INNER_JOIN to include info from different sql places
pd.read_sql("""SELECT first, last, isbn
FROM authors
INNER JOIN author_ISBN
ON authors.id = author_ISBN.id
ORDER BY last, first""",connection).head()

#qualified name syntax is sometimes needed to distinguish that have the same name potentially

    first    last        isbn
0   Abbey  Deitel  0132151006
1   Abbey  Deitel  0133406954
2  Harvey  Deitel  0134289366
3  Harvey  Deitel  0135404673
4  Harvey  Deitel  0132151006

In [36]:
# modifying time with cursor statement
cursor = connection.cursor()
cursor = cursor.execute("""INSERT INTO authors (first, last)
VALUES ('Sue', 'Red')""")
# values provided must match the column names specified both in order and type
# is also auto assigned a unique id

In [37]:
pd.read_sql('SELECT id, first, last FROM authors', connection, index_col=['id'])

        first    last
id
1        Paul  Deitel
2      Harvey  Deitel
3       Abbey  Deitel
4         Dan   Quirk
5   Alexander    Wald
6         Sue     Red

In [38]:
#update statement
cursor = cursor.execute("""UPDATE authors
SET last='Black'
WHERE last='Red' AND first='Sue'""")
#gets applied to every row w/i the where

In [39]:
cursor.rowcount

1

In [40]:
pd.read_sql('SELECT id, first, last FROM authors', connection, index_col=['id'])

        first    last
id
1        Paul  Deitel
2      Harvey  Deitel
3       Abbey  Deitel
4         Dan   Quirk
5   Alexander    Wald
6         Sue   Black

In [41]:
#delete from statement to remove rows
cursor = cursor.execute('DELETE FROM authors WHERE id=6')

In [42]:
cursor.rowcount

1

In [43]:
pd.read_sql('SELECT id, first, last FROM authors', connection, index_col=['id'])

        first    last
id
1        Paul  Deitel
2      Harvey  Deitel
3       Abbey  Deitel
4         Dan   Quirk
5   Alexander    Wald

In [44]:
#close when no longer in use
connection.close()